//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroVideo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservatie
    {
        public int klantid { get; set; }
        public int filmid { get; set; }
        public System.DateTime reservatie { get; set; }
    
        public virtual Film films { get; set; }
        public virtual Klant klant { get; set; }
    }
}
